@Host_HostAddress = http://localhost:5208

### begin new session
POST {{Host_HostAddress}}/sessions/
Accept: application/json

### end session 12345
PATCH {{Host_HostAddress}}/sessions/12345
Accept: application/json

{
    "desired-state":"done"
}

### retrieve status of session 12345
GET {{Host_HostAddress}}/sessions/12345
Accept: application/json

### trigger 1st action of session 12345
POST {{Host_HostAddress}}/sessions/12345/actions/1
Accept: application/json

### trigger 2nd action of session 12345
POST {{Host_HostAddress}}/sessions/12345/actions/2
Accept: application/json

### trigger 3rd action of session 12345
POST {{Host_HostAddress}}/session/12345/actions/3
Accept: application/json

### retrieve status of the 3rd action of session 12345
GET {{Host_HostAddress}}/session/12345/actions/3
Accept: application/json

### retrieve data from the 3rd action of session 12345
GET {{Host_HostAddress}}/session/12345/actions/3/data
Accept: application/json